# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_R9A09G077) += myb-yt2hx-base.dtb \
				myb-yt2hx-display.dtb \
				myb-yt2hx-display-canfd.dtb \
				myb-yt2hx-4-net-rs232.dtb 

# Extra DTBs for A55 support
dtb-$(CONFIG_ARCH_R9A09G077) += myb-yt2hx-fsp-a551-support.dtb
dtb-$(CONFIG_ARCH_R9A09G077) += myb-yt2hx-fsp-a552-support.dtb
dtb-$(CONFIG_ARCH_R9A09G077) += myb-yt2hx-fsp-a553-support.dtb
